{{- if .Values.pipelines.deployableResources.security }}
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
  name: image-scan-remote
spec:
  params:
    - name: IMAGE_NAMES
      description: Array of container images to scan.
    - name: CODEBASE_NAME
      description: Name of the codebase/component. Used as the DefectDojo product name.
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
        generateName: image-scan-remote-
        labels:
          app.edp.epam.com/pipelinetype: security
      spec:
        params:
          - name: IMAGE_NAMES
            value: $(tt.params.IMAGE_NAMES)
          - name: CODEBASE_NAME
            value: $(tt.params.CODEBASE_NAME)
        pipelineRef:
          name: image-scan-remote
        taskRunTemplate:
          serviceAccountName: tekton
          {{- if .Values.pipelines.podTemplate }}
          podTemplate: {{ .Values.pipelines.podTemplate | toYaml | nindent 12 }}
          {{- end }}
        workspaces:
          - name: shared-workspace
            subPath: codebase
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 5Gi
{{- end }}
