{{- if eq .Values.reporter.enabled true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edp-tekton-reporter.name" . }}
  labels:
    {{- include "edp-tekton-reporter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "edp-tekton-reporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.reporter.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "edp-tekton-reporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.reporter.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "edp-tekton-reporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.reporter.podSecurityContext | nindent 8 }}
      containers:
        - command:
          - /edpreporter
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: REPORTER_TAIL_LINES
              value: {{ .Values.reporter.tailLines | quote }}
            - name: REPORTER_COMMENT_STRATEGY
              value: {{ .Values.reporter.commentStrategy | quote }}
            - name: PORTAL_BASE_URL
              value: {{ include "edp-tekton-reporter.portalBaseUrl" . | quote }}
          name: tekton-reporter
          securityContext:
            {{- toYaml .Values.reporter.securityContext | nindent 12 }}
          image: "{{ .Values.reporter.image.repository }}:{{ .Values.reporter.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.reporter.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.reporter.resources | nindent 12 }}
          {{- with .Values.reporter.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.reporter.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.reporter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.reporter.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.reporter.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
