{{- if eq .Values.reporter.enabled true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "edp-tekton-reporter.serviceAccountName" . }}
  labels:
    {{- include "edp-tekton-reporter.labels" . | nindent 4 }}
  {{- with .Values.reporter.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
