{{ if has "gitlab" .Values.global.gitProviders }}
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: gitlab-review
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  interceptors:
    - ref:
        name: "gitlab"
        kind: ClusterInterceptor
      params:
        - name: "secretRef"
          value:
            secretName: ci-gitlab
            secretKey: secretString
        - name: "eventTypes"
          value: ["Merge Request Hook", "Note Hook"]
    - ref:
        name: "cel"
        kind: ClusterInterceptor
      params:
        # Process MR open/reopen, code pushes (update with oldrev), and comments.
        - name: "filter"
          value: "body.object_attributes.action in ['open', 'reopen'] || (body.object_attributes.action == 'update' && has(body.object_attributes.oldrev)) || (body.object_kind == 'note' && has(body.merge_request))"
    - ref:
        name: "edp"
        kind: NamespacedInterceptor
{{- include "edp-tekton.reviewInterceptorParams" . }}
  bindings:
    - ref: gitlab-binding-review
  template:
    ref: gitlab-review-template
{{ end }}
