{{ if .Values.pipelines.deployableResources.tasks }}
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: get-version-default
spec:
  description: |
    This task generates a version number for the application based on the current timestamp and the branch name.
    The version number is used to tag the image and the codebase image stream.
  params:
    - name: BRANCH_NAME
      type: string
      description: Branch name.
  results:
    - name: VERSION
      description: "Application version"
    - name: VCS_TAG
      description: "VCS tag"
    - name: IS_TAG
      description: "CodebaseImageStream tag"
    - name: TIMESTAMP
      description: Current timestamp
    - name: NORMALIZED_VERSION
      description: Normalized version
  steps:
    - name: get-timestamp
      image: {{ include "edp-tekton.registry" . }}/alpine:3.18.9
      script: |
        ts=$(date "+%Y%m%d-%H%M%S")
        nts=$(date "+%Y%m%d.%H%M%S")
        echo "Current Timestamp: ${ts}"
        echo "Current Normalized Timestamp: ${nts}"
        printf "%s" "${ts}"  > "$(results.TIMESTAMP.path)"
        printf "%s" "${nts}" > "$(results.NORMALIZED_VERSION.path)"

    - name: get-version
      image: {{ include "edp-tekton.registry" . }}/alpine:3.18.9
      env:
        - name: BRANCH_NAME
          value: "$(params.BRANCH_NAME)"
      script: |
        set -e

        BUILD_VERSION=$(cat $(results.TIMESTAMP.path))
        NORMALIZED_BRANCH=$(printf '%s' "${BRANCH_NAME}" | sed 's/\//-/g')
        VCS_TAG="${NORMALIZED_BRANCH}-${BUILD_VERSION}"
        IS_TAG="${VCS_TAG}"

        echo "Application version - ${BUILD_VERSION}"
        echo "VCS tag - ${VCS_TAG}"
        echo "IS tag - ${IS_TAG}"

        printf "%s" "${BUILD_VERSION}" > "$(results.VERSION.path)"
        printf "%s" "${VCS_TAG}"       > "$(results.VCS_TAG.path)"
        printf "%s" "${IS_TAG}"        > "$(results.IS_TAG.path)"
{{ end }}
