apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-security
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
{{- with .Values.pipelines.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-security
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
rules:
  # image-scan-chart reads the image reference from the codebase image stream
  - apiGroups:
      - v2.edp.epam.com
    resources:
      - codebaseimagestreams
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-security
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: tekton-security
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-security
