apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-unprivileged
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- with .Values.pipelines.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
